### PR TITLE
Adding config file and improving user interface

### PR DESCRIPTION
**Pull request by n-swan**
Added config file for Azure Web-Services

### CODE REVIEW

**Comment by adello-medium** [comment]
Hi this is some basic content for the emails.

**Comment by mazizam** [comment]
Nice implementation !

**Comment by adello-medium** [comment]
i dont understand the math behind

**Comment by GilgusMaximus** [comment]
Hellooo

**Comment by GilgusMaximus** [comment]
This code looks very nice.

**Comment by mazizam** [comment]
I complement you on what you did

**Comment by GilgusMaximus** [comment]
This is a very long long text. You did very well with you latest pul lrequests. Keep up the good work #100. So let's have a cup of water at some time together :)

**Comment by mazizam** [comment]
Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad Salad

**Comment by n-swan** [comment]
> 
> 
> I complement you on what you did

Thank you. I appreciate it very much.

**Pull request closed without merging**
